# Generated by Django 5.0.1 on 2026-04-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosensor_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='device_id',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='emg_filtered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='emg_rms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='emg_rms_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='imu_calibrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='imu_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='pitch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='roll',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ts_ms',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='wifi_rssi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='acc_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='acc_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='acc_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='emg_raw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='emg_voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='gyro_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='gyro_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='gyro_z',
            field=models.FloatField(default=0.0),
        ),
    ]
