# Generated by Django 5.0.1 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosensor_api', '0002_sensorreading_device_id_sensorreading_emg_filtered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='emg_filtered',
            field=models.TextField(default='0'),
        ),
    ]
